version: '3'
services:
  fpm:
    build: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./app/src/www:/usr/share/nginx/html
      # Your php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    links:
      - mysql
      - mongo
      - redis

  swoole:
    build: ./php-fpm
    ports:
      - "9501"
    volumes:
      - ./app/src/swoole:/var/www/html
      # Your php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    links:
      - mysql
      - mongo
      - redis
    command: php /var/www/html/server.php

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
  #    - "443:443"
    volumes:
      # app
      - ./app/src/www:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
#      - ./nginx/log/:/var/log/nginx/:ro
      # certificates
  #    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
  #    - ./nginx/ca/server.key/:/etc/nginsudox/server.key:ro
    depends_on:
      - fpm
      - swoole
    links:
      - fpm
      - swoole

  mysql:
    image: mysql:latest
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d:ro
#      - ./mysql/log:/var/log/mysql/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mongo:
    build: ./mongo
    ports:
      # Allow client to access 27017
      - "27017:27017"
    volumes:
      # NOTE: your data will be stored in ./mongo
      - ./mongo/data:/data/db
      - ./mongo/conf:/data/configdb:ro

  redis:
    build: ./redis
    ports:
      # Allow client to access 6379
      - "6379:6379"
    volumes:
      # NOTE: your data will be stored in ./redis
      - ./redis/data:/data
      - ./redis/conf/:/usr/local/etc/redis/:ro